version: '3'
services:
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    depends_on:
      - database

  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=userdb
